name: Build

on:
  workflow_dispatch:
  push:
    branches: ['main-thread-network']

jobs:
  server:
    name: Server component (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
    uses: ./.github/workflows/build-server-reusable.yml
    with:
      target: ServerOmp
      arch: ${{ matrix.arch }}
      build-type: Release

  client:
    name: Client files
    uses: ./.github/workflows/build-client-reusable.yml
    with:
      version: 1.3.0-fix
      cef-version: 148.0.10+g7ee53f5+chromium-148.0.7778.218
      cef-arch: windows32
      build-type: Release
